language: node_js
node_js:
  - "10"

install: 
  - npm install
  - cd projects/api && npm install && cd ../..

script: 
  - npm test

before_deploy: cd projects/api

deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $HEROKU_API_KEY
  app: iffr-api
  on: master