language: node_js
node_js:
  - "10"

install: 
  - npm install
  - cd projects/api
  - npm install
  - cd ../matcher 
  - npm install 
  - cd ../..

script: 
  - npm test
  - cd projects/matcher
  - npm run build

before_deploy: cd ../api

deploy:
  - provider: pages
    local-dir: ../matcher
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on: master
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: iffr-api
    on: master